name: CI on macOS
on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'master'
      - 'gh-pages'
  pull_request:

env:
  CMAKE_VERSION: 3.8.2
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-10.15
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            build: snippet
            build_type: Release

          - name: "gcc10"
            cxx: "g++-10"
            cc: "gcc-10"
            build: snippet
            build_type: Release

          - name: "gcc9 (c++2a)"
            cxx: "g++-9"
            cc: "gcc-9"
            build: snippet
            build_type: Release
            cxx_flags: "-std=c++2a"

          - name: "gcc8"
            cxx: "g++-8"
            cc: "gcc-8"
            build: snippet
            build_type: Release

          - name: "gcc7"
            cxx: "g++-7"
            cc: "gcc-7"
            build: snippet
            build_type: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: learning_resources
          fetch-depth: 2
          submodules: recursive

      - name: Configure Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install CMake
        run: bash ./learning_resources/submodules/seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install ccache
        run: bash ./learning_resources/submodules/seqan3/.github/workflows/scripts/install_via_brew.sh ccache

      - name: Install compiler ${{ matrix.cxx }}
        run: bash ./learning_resources/submodules/seqan3/.github/workflows/scripts/install_via_brew.sh gcc $(echo "${{ matrix.cxx }}" | sed "s/g++-//g")

      - name: Load ccache
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../learning_resources/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"

      - name: Build tests
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 6
          CCACHE_MAXSIZE: 500M
        run: |
          ccache -p || true
          cd build
          make -k -j3
          ccache -s || true

      - name: Run tests
        run: |
          cd build
          ctest . -j3 --output-on-failure
